import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar/navbar";
import { Movie } from "@/generated/prisma";
import MoviePage from "./movie/page";

export const metadata: Metadata = {
  title: "Movie Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body> 
      <Navbar />
      {children}
      </body>
    </html>
  );
}
